# Generated by Django 5.2.5 on 2025-08-15 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('tabela_precos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tabela de Preços')),
                ('condicoes_pagamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condições de Pagamento')),
                ('faturamento_ultimos_12m', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Faturamento (Últimos 12M)')),
                ('volume_medio_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Volume Médio por Pedido')),
                ('frequencia_compra_dias', models.IntegerField(default=0, verbose_name='Frequência de Compra (dias)')),
                ('prazo_medio_pagamento_dias', models.IntegerField(default=0, verbose_name='Prazo Médio de Pagamento (dias)')),
                ('score_potencial', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Score de Potencial')),
                ('curva_classificacao', models.CharField(blank=True, choices=[('A', 'Curva A'), ('B', 'Curva B'), ('C', 'Curva C')], max_length=1, null=True, verbose_name='Curva de Classificação')),
                ('data_ultima_compra', models.DateField(blank=True, null=True, verbose_name='Data da Última Compra')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Vendedor')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Contato')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='gestao.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.vendedor', verbose_name='Vendedor Responsável'),
        ),
        migrations.CreateModel(
            name='ClienteProdutoMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_sku', models.CharField(max_length=50, verbose_name='SKU do Produto')),
                ('produto_nome', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_produtos', to='gestao.cliente', verbose_name='Cliente')),
            ],
            options={
                'unique_together': {('cliente', 'produto_sku')},
            },
        ),
    ]
