# Generated by Django 5.2.5 on 2025-08-15 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_tarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('contato_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Contato')),
                ('contato_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('etapa_funil', models.CharField(choices=[('prospect', 'Prospect'), ('contato_inicial', 'Contato Inicial'), ('proposta', 'Envio de Proposta'), ('negociacao', 'Negociação'), ('fechado_ganho', 'Fechado (Ganho)'), ('fechado_perdido', 'Fechado (Perdido)')], default='prospect', max_length=20, verbose_name='Etapa do Funil')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Estimado da Oportunidade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('vendedor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.vendedor', verbose_name='Vendedor Responsável')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
